# Generated by Django 3.0.7 on 2020-07-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
