# Generated by Django 3.0.7 on 2020-07-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_chat_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
