# Generated by Django 3.0.7 on 2020-07-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
