# Generated by Django 3.0.7 on 2020-07-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_auto_20200705_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='room',
            field=models.TextField(blank=True, null=True),
        ),
    ]
