# Generated by Django 3.0.7 on 2020-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200709_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
