# Generated by Django 2.2.14 on 2020-08-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delivery_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
