# Generated by Django 2.2.14 on 2020-08-25 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_shippingaddress_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_orders_added', to=settings.AUTH_USER_MODEL)),
                ('checkout_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_orders_checkedout', to=settings.AUTH_USER_MODEL)),
                ('order_items', models.ManyToManyField(blank=True, related_name='orders_shared', to='shop.OrderItem')),
            ],
        ),
    ]
