# Generated by Django 3.0.7 on 2020-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundi',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
